package it.polimi.ingsw.ps14.client.view.gui;

import it.polimi.ingsw.ps14.client.Communication;
import it.polimi.ingsw.ps14.model.ItemForSale;
import it.polimi.ingsw.ps14.model.Market;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author nicol
 */
public class BuyDialog extends javax.swing.JDialog {

        private final Market market;
	private final transient Integer playerID;
	private final transient Communication communication;
	
    /**
     * Creates new form BuyDialog
     */
    public BuyDialog(java.awt.Frame parent, boolean modal, Integer playerID, Communication communication,Market market) {
        super(parent, modal);
		this.playerID = playerID;
		this.communication = communication;
                this.market=market;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        buyButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        barCodeTextField = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(32767, 0));
        assistantsTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        marketDisplay = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Buy an object");

        buyButton.setText("Buy");
        buyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buyButtonActionPerformed(evt);
            }
        });

        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.LINE_AXIS));

        jLabel2.setText("BarCode of the item you want to buy");
        jPanel2.add(jLabel2);
        jPanel2.add(filler1);
        jPanel2.add(barCodeTextField);

        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.LINE_AXIS));

        jLabel3.setText("Nr of assistants to buy (optional)");
        jPanel3.add(jLabel3);
        jPanel3.add(filler3);

        assistantsTextField.setPreferredSize(new java.awt.Dimension(50, 32));
        jPanel3.add(assistantsTextField);

        marketDisplay.setLayout(new java.awt.GridLayout(0, 1));
        jScrollPane1.setViewportView(marketDisplay);
        for(ItemForSale it:market.getObjectsForSale()){
            JLabel lv=new JLabel ();
            lv.setText(it.toString());
            lv.setFont(new java.awt.Font("Arial", 0, 11));
            marketDisplay.add(lv);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(152, 152, 152)
                                .addComponent(buyButton))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(131, 131, 131)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 27, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buyButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buyButtonActionPerformed
		String barCodeText = barCodeTextField.getText();
		if (barCodeText.isEmpty()) {
			communication.doneFinishBuying(playerID);
			dispose();
			return;
		}
		
		Integer barCode;
		try {
			barCode = Integer.valueOf(barCodeText);
		} catch (NumberFormatException e) {
			JOptionPane.showMessageDialog(null, "You can only enter numbers in the barcode field", "Warning", JOptionPane.WARNING_MESSAGE);
			return;
		}
		
		String assistantsText = assistantsTextField.getText();
		if (assistantsText.isEmpty()) {
			communication.buy(playerID, barCode, null);
			dispose();
		} else {
			Integer numAssistants;
			try {
				numAssistants = Integer.valueOf(assistantsText);
			} catch (NumberFormatException e) {
				JOptionPane.showMessageDialog(null, "You can only enter numbers in the assistants field", "Warning", JOptionPane.WARNING_MESSAGE);
				return;
			}
			
			communication.buy(playerID, barCode, numAssistants);
			dispose();
		}
    }//GEN-LAST:event_buyButtonActionPerformed

 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField assistantsTextField;
    private javax.swing.JTextField barCodeTextField;
    private javax.swing.JButton buyButton;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel marketDisplay;
    // End of variables declaration//GEN-END:variables
}
