/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package it.polimi.ingsw.ps14.client.view.gui;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.swing.JLabel;

/**
 *
 * @author peter
 */
public class EndResultsDialog extends javax.swing.JDialog {

	private final transient Integer playerID;
	private final transient List<List<String>> endResults;
	
	/**
	 * Creates new form NobilityRequestDialog
	 */
	public EndResultsDialog(java.awt.Frame parent, boolean modal, Integer playerID, List<List<String>> endResults) {
		super(parent, "Game Results", modal);
		this.playerID = playerID;
		this.endResults = endResults;
		
		initComponents();
				
		// set description
		winnerLabel.setText(String.format("<html><b>The winner is %s!</b></html>", endResults.get(0).get(1)));
		winnerLabel.repaint();
		winnerLabel.revalidate();
		
		// set description number of choices
        if (playerID.equals(Integer.valueOf(endResults.get(0).get(0)))) {
            youwonLabel.setText("<html><b>Congratulations! You won!</b></html>");
        } else {
			youwonLabel.setText("");
		}
		youwonLabel.repaint();
		youwonLabel.revalidate();
		
		// build a jlabel for each player
		resultsPanel.setLayout(new java.awt.GridLayout(endResults.size(), 0));
		for (int i = 0; i < endResults.size(); i++) {
            List<String> plrRes = endResults.get(i);
            JLabel label = new JLabel();
			label.setText(String.format("<html>%d) %s with %s points, %s assistants, %s cards, %s emporiums,  %s nobility,  %s permits,  %s coins.<br></html>", 
				i, plrRes.get(1), plrRes.get(2), plrRes.get(3), plrRes.get(4), 
				plrRes.get(5), plrRes.get(6), plrRes.get(7), plrRes.get(8)));

			resultsPanel.add(label);

			resultsPanel.repaint();
			resultsPanel.revalidate();
		}

		pack();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        resultsPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        youwonLabel = new javax.swing.JLabel();
        winnerLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        okButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        resultsPanel.setLayout(new java.awt.GridLayout(200, 0));
        jScrollPane1.setViewportView(resultsPanel);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel1.setLayout(new java.awt.BorderLayout());

        youwonLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        youwonLabel.setText("[Congratulations, you won!]");
        jPanel1.add(youwonLabel, java.awt.BorderLayout.CENTER);

        winnerLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        winnerLabel.setText("[The winner is x]");
        jPanel1.add(winnerLabel, java.awt.BorderLayout.PAGE_START);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });
        jPanel2.add(okButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, -1, -1));

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
		dispose();
    }//GEN-LAST:event_okButtonActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
    }//GEN-LAST:event_formWindowClosed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(EndResultsDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(EndResultsDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(EndResultsDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(EndResultsDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>
		//</editor-fold>

		/* Create and display the dialog */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				List<String> player1 = new ArrayList<>(Arrays.asList("1", "ubaldo", "50", "3", "5", "10", "4", "7", "2"));
				List<String> player2 = new ArrayList<>(Arrays.asList("2", "pinco", "42", "5", "6", "9", "4", "8", "1"));
				List<List<String>> endResults = new ArrayList<>();
				endResults.add(player1);
				endResults.add(player2);
				
				EndResultsDialog dialog = new EndResultsDialog(new javax.swing.JFrame(), true, 1, endResults);
				dialog.addWindowListener(new java.awt.event.WindowAdapter() {
					@Override
					public void windowClosing(java.awt.event.WindowEvent e) {
						System.exit(0);
					}
				});
				dialog.setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton okButton;
    private javax.swing.JPanel resultsPanel;
    private javax.swing.JLabel winnerLabel;
    private javax.swing.JLabel youwonLabel;
    // End of variables declaration//GEN-END:variables
}
