package it.polimi.ingsw.ps14.client.view.gui;

import it.polimi.ingsw.ps14.client.Communication;
import it.polimi.ingsw.ps14.model.Balcony;
import it.polimi.ingsw.ps14.model.BusinessPermit;
import it.polimi.ingsw.ps14.model.ColorCouncillor;
import it.polimi.ingsw.ps14.model.ColorPolitic;
import it.polimi.ingsw.ps14.model.RegionType;
import java.awt.Color;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JLayeredPane;
import javax.swing.JPanel;
import javax.swing.JTextArea;
import javax.swing.OverlayLayout;
import javax.swing.SwingUtilities;
import javax.swing.text.DefaultCaret;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
@SuppressWarnings("serial")
public class GUI extends javax.swing.JFrame {

    private Integer playerID;
    private Communication communication;
    private String name;

    private final Map<ColorPolitic, ImageIcon> politicCard;
    private final Map<ColorCouncillor, ImageIcon> councillor;

//    private final Image politicPink;
//    private final Image politicWhite;
//    private final Image politicPurple;
//    private final Image politicJolly;
//    private final Image politicOrange;
//    private final Image politicBlue;
//    private final Image politicBlack;
    public GUI(Integer playerID, String name, Communication communication) {
        initComponents();
        this.playerID = playerID;
        this.name = name;
        this.communication = communication;

        politicCard = new HashMap<>();
        politicCard.put(ColorPolitic.PINK, new javax.swing.ImageIcon(getClass().getResource("/resource/image/politics/pink.png")));
        politicCard.put(ColorPolitic.PURPLE, new javax.swing.ImageIcon(getClass().getResource("/resource/image/politics/purple.png")));
        politicCard.put(ColorPolitic.BLUE, new javax.swing.ImageIcon(getClass().getResource("/resource/image/politics/blue.png")));
        politicCard.put(ColorPolitic.ORANGE, new javax.swing.ImageIcon(getClass().getResource("/resource/image/politics/orange.png")));
        politicCard.put(ColorPolitic.WHITE, new javax.swing.ImageIcon(getClass().getResource("/resource/image/politics/white.png")));
        politicCard.put(ColorPolitic.BLACK, new javax.swing.ImageIcon(getClass().getResource("/resource/image/politics/black.png")));
        politicCard.put(ColorPolitic.JOLLY, new javax.swing.ImageIcon(getClass().getResource("/resource/image/politics/jolly.png")));

        councillor = new HashMap<>();
        councillor.put(ColorCouncillor.PINK, new javax.swing.ImageIcon(getClass().getResource("/resource/image/councillors/pink.png")));
        councillor.put(ColorCouncillor.PURPLE, new javax.swing.ImageIcon(getClass().getResource("/resource/image/councillors/purple.png")));
        councillor.put(ColorCouncillor.BLUE, new javax.swing.ImageIcon(getClass().getResource("/resource/image/councillors/blue.png")));
        councillor.put(ColorCouncillor.ORANGE, new javax.swing.ImageIcon(getClass().getResource("/resource/image/councillors/orange.png")));
        councillor.put(ColorCouncillor.WHITE, new javax.swing.ImageIcon(getClass().getResource("/resource/image/councillors/white.png")));
        councillor.put(ColorCouncillor.BLACK, new javax.swing.ImageIcon(getClass().getResource("/resource/image/councillors/black.png")));

    }

    public void setCommunication(Communication communication) {
        this.communication = communication;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jMenu1 = new javax.swing.JMenu();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jDialog1 = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        overlay = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        chatArea = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        infoArea = new javax.swing.JTextArea();
        coastBalcony = new javax.swing.JPanel();
        hillsBalcony = new javax.swing.JPanel();
        mountBalcony = new javax.swing.JPanel();
        mountC4 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        profile = new javax.swing.JLayeredPane();
        assistants = new javax.swing.JLabel();
        coins = new javax.swing.JLabel();
        victoryPoints = new javax.swing.JLabel();
        nobility = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        acquirePermitButton = new javax.swing.JButton();
        buildEmporiumWithKingButton = new javax.swing.JButton();
        electCouncillorButton = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        changePermitTilesButton = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        electWithAssistantButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        drawButton = new javax.swing.JButton();
        showPermit = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        userProfile = new javax.swing.JLayeredPane();
        jLabel4 = new javax.swing.JLabel();
        permitHills = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        permitCoast = new javax.swing.JPanel();
        coastPer1 = new javax.swing.JLabel();
        coastPer2 = new javax.swing.JLabel();
        permitMount = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        kingBalcony = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        kingBonus = new javax.swing.JLabel();
        nobilityTrack = new javax.swing.JLayeredPane();
        jLabel5 = new javax.swing.JLabel();

        jMenu1.setText("jMenu1");

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        overlay.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        overlay.setMaximumSize(new java.awt.Dimension(1000, 1000));
        overlay.setMinimumSize(new java.awt.Dimension(100, 100));
        overlay.setLayout(new javax.swing.OverlayLayout(overlay));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Map/mappa coste a.png"))); // NOI18N
        overlay.add(jLabel7);

        jPanel1.add(overlay);
        overlay.setLayout(new OverlayLayout(overlay));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Map/mappa colline b.png"))); // NOI18N
        jPanel1.add(jLabel9);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Map/mappa monte a.png"))); // NOI18N
        jPanel1.add(jLabel1);

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder("CHAT"));

        chatArea.setEditable(false);
        DefaultCaret caret = (DefaultCaret)infoArea.getCaret();
        caret.setUpdatePolicy(DefaultCaret.ALWAYS_UPDATE);
        chatArea.setColumns(20);
        chatArea.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        chatArea.setRows(5);
        jScrollPane1.setViewportView(chatArea);

        DefaultCaret caretInfo = (DefaultCaret)infoArea.getCaret();
        caretInfo.setUpdatePolicy(DefaultCaret.ALWAYS_UPDATE);
        infoArea.setEditable(false);
        infoArea.setColumns(20);
        infoArea.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        infoArea.setRows(5);
        jScrollPane3.setViewportView(infoArea);

        coastBalcony.setBackground(new java.awt.Color(184, 204, 246));

        hillsBalcony.setBackground(new java.awt.Color(171, 253, 112));

        mountBalcony.setBackground(new java.awt.Color(200, 184, 179));
        mountBalcony.add(mountC4);

        profile.setBorder(javax.swing.BorderFactory.createTitledBorder(null, name, javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        profile.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 15, 5));

        assistants.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/image/bonus/assistants.png"))); // NOI18N
        assistants.setText("0");
        profile.add(assistants);

        coins.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/image/bonus/coins.png"))); // NOI18N
        coins.setText("0");
        profile.add(coins);

        victoryPoints.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/image/bonus/victorypoints.png"))); // NOI18N
        victoryPoints.setText("0");
        profile.add(victoryPoints);

        nobility.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/image/bonus/nobilitypoints.png"))); // NOI18N
        nobility.setText("0");
        profile.add(nobility);

        jLabel2.setFont(new java.awt.Font("Georgia", 1, 11)); // NOI18N
        jLabel2.setText("MAIN ACTIONS");

        acquirePermitButton.setText("Acquire Permit");
        acquirePermitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acquirePermitButtonActionPerformed(evt);
            }
        });

        buildEmporiumWithKingButton.setText("Build Emporium With King");
        buildEmporiumWithKingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buildEmporiumWithKingButtonActionPerformed(evt);
            }
        });

        electCouncillorButton.setText("Elect Councillor ");
        electCouncillorButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        electCouncillorButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                electCouncillorButtonMouseClicked(evt);
            }
        });
        electCouncillorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                electCouncillorButtonActionPerformed(evt);
            }
        });

        jButton5.setText("Build Emporium With Permit");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(acquirePermitButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(electCouncillorButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buildEmporiumWithKingButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(acquirePermitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(electCouncillorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buildEmporiumWithKingButton, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, Short.MAX_VALUE)
                .addContainerGap())
        );

        changePermitTilesButton.setText("Change Permit Tiles");
        changePermitTilesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changePermitTilesButtonActionPerformed(evt);
            }
        });

        jButton2.setText("Engage Assistant");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton8.setText("Additional Main Action");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        electWithAssistantButton.setText("Elect Councillor with Assistant");
        electWithAssistantButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                electWithAssistantButtonMouseClicked(evt);
            }
        });
        electWithAssistantButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                electWithAssistantButtonActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Georgia", 1, 11)); // NOI18N
        jLabel3.setText("QUICK ACTIONS");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(changePermitTilesButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(electWithAssistantButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(changePermitTilesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(electWithAssistantButton, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jButton3.setText("Pass");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        drawButton.setText("DRAW");
        drawButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                drawButtonMouseClicked(evt);
            }
        });

        showPermit.setText("Show my permit");
        showPermit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showPermitMouseClicked(evt);
            }
        });
        showPermit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showPermitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(drawButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(showPermit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(showPermit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(drawButton)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 49, Short.MAX_VALUE))
                    .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        userProfile.setBackground(new java.awt.Color(223, 32, 32));
        userProfile.setLayout(new java.awt.GridBagLayout());

        jLabel4.setText("playerInfo");
        userProfile.add(jLabel4, new java.awt.GridBagConstraints());

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(profile, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(profile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(userProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        permitHills.setLayout(new java.awt.GridLayout());

        jLabel11.setText("P1");
        permitHills.add(jLabel11);

        jLabel12.setText("P2");
        permitHills.add(jLabel12);

        permitCoast.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        permitCoast.setLayout(new java.awt.GridLayout());

        coastPer1.setText("P1");
        permitCoast.add(coastPer1);

        coastPer2.setText("P2");
        permitCoast.add(coastPer2);

        permitMount.setLayout(new java.awt.GridLayout());

        jLabel13.setText("P1");
        permitMount.add(jLabel13);

        jLabel14.setText("P2");
        permitMount.add(jLabel14);

        kingBalcony.setBackground(new java.awt.Color(254, 224, 103));

        jLabel15.setText("KING");

        jTextField1.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N

        jButton1.setText("Send");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        kingBonus.setFont(new java.awt.Font("SFNS Display", 0, 11)); // NOI18N
        kingBonus.setText("King bonus:");

        nobilityTrack.setLayout(new java.awt.GridLayout(12, 1, 0, 2));

        jLabel5.setText("nobility track");
        nobilityTrack.add(jLabel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 0, Short.MAX_VALUE))
                                .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(coastBalcony, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(permitCoast, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(permitHills, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(permitMount, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(hillsBalcony, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(mountBalcony, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel15)
                    .addComponent(kingBalcony, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kingBonus, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
                    .addComponent(nobilityTrack))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(hillsBalcony, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(coastBalcony, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(mountBalcony, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(permitMount, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(permitHills, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(permitCoast, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane3)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(7, 7, 7)
                        .addComponent(kingBalcony, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(kingBonus, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nobilityTrack, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void changePermitTilesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changePermitTilesButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_changePermitTilesButtonActionPerformed

    private void electWithAssistantButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_electWithAssistantButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_electWithAssistantButtonActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void buildEmporiumWithKingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buildEmporiumWithKingButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buildEmporiumWithKingButtonActionPerformed

    private void acquirePermitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acquirePermitButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_acquirePermitButtonActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void electCouncillorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_electCouncillorButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_electCouncillorButtonActionPerformed

    private void electCouncillorButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_electCouncillorButtonMouseClicked

//        ElectCouncillorDialog electCouncillorDialog = new ElectCouncillorDialog(this, true, playerID, communication);
        ElectCouncillorDialog electCouncillorDialog = new ElectCouncillorDialog(this, true);
        electCouncillorDialog.setPlayerID(playerID);
        electCouncillorDialog.setCommunication(communication);
        electCouncillorDialog.setVisible(true);
        electCouncillorDialog.setAlwaysOnTop(rootPaneCheckingEnabled);
    }//GEN-LAST:event_electCouncillorButtonMouseClicked

    private void drawButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_drawButtonMouseClicked
        communication.drawCard(playerID);
    }//GEN-LAST:event_drawButtonMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3MouseClicked

    private void electWithAssistantButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_electWithAssistantButtonMouseClicked
        ElectWithAssistantDialog electWithAssistantDialog = new ElectWithAssistantDialog(this, true);
        electWithAssistantDialog.setPlayerID(playerID);
        electWithAssistantDialog.setCommunication(communication);
        electWithAssistantDialog.setVisible(true);
        electWithAssistantDialog.setAlwaysOnTop(rootPaneCheckingEnabled);
    }//GEN-LAST:event_electWithAssistantButtonMouseClicked

    private void showPermitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showPermitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_showPermitActionPerformed

    private void showPermitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showPermitMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_showPermitMouseClicked

    public static void start() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new GUI(playerID,communication).setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton acquirePermitButton;
    private javax.swing.JLabel assistants;
    private javax.swing.JButton buildEmporiumWithKingButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton changePermitTilesButton;
    private javax.swing.JTextArea chatArea;
    private javax.swing.JPanel coastBalcony;
    private javax.swing.JLabel coastPer1;
    private javax.swing.JLabel coastPer2;
    private javax.swing.JLabel coins;
    private javax.swing.JButton drawButton;
    private javax.swing.JButton electCouncillorButton;
    private javax.swing.JButton electWithAssistantButton;
    private javax.swing.JPanel hillsBalcony;
    private javax.swing.JTextArea infoArea;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton8;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPanel kingBalcony;
    private javax.swing.JLabel kingBonus;
    private javax.swing.JPanel mountBalcony;
    private javax.swing.JLabel mountC4;
    private javax.swing.JLabel nobility;
    private javax.swing.JLayeredPane nobilityTrack;
    private javax.swing.JPanel overlay;
    private javax.swing.JPanel permitCoast;
    private javax.swing.JPanel permitHills;
    private javax.swing.JPanel permitMount;
    private javax.swing.JLayeredPane profile;
    private javax.swing.JButton showPermit;
    private javax.swing.JLayeredPane userProfile;
    private javax.swing.JLabel victoryPoints;
    // End of variables declaration//GEN-END:variables

    public void setPlayerName(String name) {
        this.name = name;
        profile.setBorder(javax.swing.BorderFactory.createTitledBorder(null, name, javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

    }

    public JTextArea getChatArea() {
        return chatArea;
    }

    public JTextArea getInfoArea() {
        return infoArea;
    }

    public JLabel getAssistants() {
        return assistants;
    }

    public JLabel getNobility() {
        return nobility;
    }

    public JLabel getCoins() {
        return coins;
    }

    public JLabel getVictoryPoints() {
        return victoryPoints;
    }

    public JLayeredPane getUserProfile() {
        return userProfile;
    }

    public void showPoliticCard(ColorPolitic c) {
        JLabel politic = (new javax.swing.JLabel());
        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                if (c == ColorPolitic.BLACK) {
                    politic.setIcon(politicCard.get(ColorPolitic.BLACK));
                }
                if (c == ColorPolitic.ORANGE) {
                    politic.setIcon(politicCard.get(ColorPolitic.ORANGE));
                }
                if (c == ColorPolitic.BLUE) {
                    politic.setIcon(politicCard.get(ColorPolitic.BLUE));
                }
                if (c == ColorPolitic.JOLLY) {
                    politic.setIcon(politicCard.get(ColorPolitic.JOLLY));
                }
                if (c == ColorPolitic.PINK) {
                    politic.setIcon(politicCard.get(ColorPolitic.PINK));
                }
                if (c == ColorPolitic.PURPLE) {
                    politic.setIcon(politicCard.get(ColorPolitic.PURPLE));
                }
                if (c == ColorPolitic.WHITE) {
                    politic.setIcon(politicCard.get(ColorPolitic.WHITE));

                }
                userProfile.add(politic);
                userProfile.revalidate();
            }
        });
    }

    public void showCouncillor(Balcony b, RegionType rt) {
        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                JLabel coun;
                JPanel balc = null;
                if (rt == RegionType.COAST) {
                    coastBalcony.removeAll();
                    balc = coastBalcony;

                }
                if (rt == RegionType.HILLS) {
                    hillsBalcony.removeAll();
                    balc = hillsBalcony;

                }
                if (rt == RegionType.MOUNTAINS) {
                    mountBalcony.removeAll();
                    balc = mountBalcony;

                }
                if (rt == null) {
                    kingBalcony.removeAll();
                    balc = kingBalcony;

                }
                // colorare le carte

                for (ColorCouncillor c : b.readBalcony()) {
                    coun = new javax.swing.JLabel();
                    if (c == ColorCouncillor.BLACK) {
                        coun.setIcon(councillor.get(ColorCouncillor.BLACK));
                    }
                    if (c == ColorCouncillor.ORANGE) {
                        coun.setIcon(councillor.get(ColorCouncillor.ORANGE));
                    }
                    if (c == ColorCouncillor.BLUE) {
                        coun.setIcon(councillor.get(ColorCouncillor.BLUE));
                    }
                    if (c == ColorCouncillor.PINK) {
                        coun.setIcon(councillor.get(ColorCouncillor.PINK));
                    }
                    if (c == ColorCouncillor.PURPLE) {
                        coun.setIcon(councillor.get(ColorCouncillor.PURPLE));
                    }
                    if (c == ColorCouncillor.WHITE) {
                        coun.setIcon(councillor.get(ColorCouncillor.WHITE));
                    }
                    if (balc != null) {
                        balc.add(coun);
                        balc.revalidate();
                    }

                }

            }
        });
    }

    public JPanel getCoastBalcony() {
        return coastBalcony;
    }

    public JPanel getHillsBalcony() {
        return hillsBalcony;
    }

    public JPanel getMountBalcony() {
        return mountBalcony;
    }

    public JPanel getKingBalcony() {
        return kingBalcony;
    }

    public JLabel getkingBonus() {
        return kingBonus;
    }

    public JLayeredPane getnobilityTrack() {
        return nobilityTrack;
    }

    public void showPermit(BusinessPermit[] bp, RegionType rt) {
        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                JPanel reg = null;
                JLabel per;
                if (rt == RegionType.COAST) {
                    reg = permitCoast;
                }
                if (rt == RegionType.HILLS) {
                    reg = permitHills;
                }
                if (rt == RegionType.MOUNTAINS) {
                    reg = permitMount;
                }
                if (reg != null) {
                    reg.removeAll();
                    for (BusinessPermit b : bp) {
                        per = new JLabel("<html>ID: " + b.getId() + "<br>City:" + b.getCityNames().toString() + "<br>Bonus:" + b.getBonusList().toString()+"</html>");
                        per.setFont(new java.awt.Font("Arial", 0, 11));
                        per.setVisible(true);
                        reg.add(per);
                    }
                }
            }

        });
    }
}
