package it.polimi.ingsw.ps14.client.view.gui;

import java.awt.Point;
import java.util.HashMap;
import java.util.Map;

import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JLayeredPane;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextArea;
import javax.swing.OverlayLayout;
import javax.swing.SwingUtilities;
import javax.swing.text.DefaultCaret;

import it.polimi.ingsw.ps14.client.Communication;
import it.polimi.ingsw.ps14.model.Balcony;
import it.polimi.ingsw.ps14.model.BusinessPermit;
import it.polimi.ingsw.ps14.model.City;
import it.polimi.ingsw.ps14.model.ColorCity;
import it.polimi.ingsw.ps14.model.ColorCouncillor;
import it.polimi.ingsw.ps14.model.ColorPolitic;
import it.polimi.ingsw.ps14.model.GamePhase;
import it.polimi.ingsw.ps14.model.MarketState;
import it.polimi.ingsw.ps14.model.RegionType;
import it.polimi.ingsw.ps14.model.State;
import java.awt.Color;
import java.awt.MouseInfo;
import java.awt.Point;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.awt.event.MouseMotionListener;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.ToolTipManager;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
@SuppressWarnings("serial")
public class GUI extends javax.swing.JFrame {

    private transient Integer playerID;
    private transient Communication communication;
    private transient String name;
    private transient State state;

    private final transient Map<ColorPolitic, ImageIcon> politicCard;
    private final transient Map<ColorCouncillor, ImageIcon> councillor;

//    private final Image politicPink;
//    private final Image politicWhite;
//    private final Image politicPurple;
//    private final Image politicJolly;
//    private final Image politicOrange;
//    private final Image politicBlue;
//    private final Image politicBlack;
    public GUI(Integer playerID, String name, Communication communication) {
        this.name = name;
        initComponents();
        this.playerID = playerID;
        this.communication = communication;

        politicCard = new HashMap<>();
        politicCard.put(ColorPolitic.PINK, new javax.swing.ImageIcon(getClass().getResource("/resource/image/politics/pink.png")));
        politicCard.put(ColorPolitic.PURPLE, new javax.swing.ImageIcon(getClass().getResource("/resource/image/politics/purple.png")));
        politicCard.put(ColorPolitic.BLUE, new javax.swing.ImageIcon(getClass().getResource("/resource/image/politics/blue.png")));
        politicCard.put(ColorPolitic.ORANGE, new javax.swing.ImageIcon(getClass().getResource("/resource/image/politics/orange.png")));
        politicCard.put(ColorPolitic.WHITE, new javax.swing.ImageIcon(getClass().getResource("/resource/image/politics/white.png")));
        politicCard.put(ColorPolitic.BLACK, new javax.swing.ImageIcon(getClass().getResource("/resource/image/politics/black.png")));
        politicCard.put(ColorPolitic.JOLLY, new javax.swing.ImageIcon(getClass().getResource("/resource/image/politics/jolly.png")));

        councillor = new HashMap<>();
        councillor.put(ColorCouncillor.PINK, new javax.swing.ImageIcon(getClass().getResource("/resource/image/councillors/pink.png")));
        councillor.put(ColorCouncillor.PURPLE, new javax.swing.ImageIcon(getClass().getResource("/resource/image/councillors/purple.png")));
        councillor.put(ColorCouncillor.BLUE, new javax.swing.ImageIcon(getClass().getResource("/resource/image/councillors/blue.png")));
        councillor.put(ColorCouncillor.ORANGE, new javax.swing.ImageIcon(getClass().getResource("/resource/image/councillors/orange.png")));
        councillor.put(ColorCouncillor.WHITE, new javax.swing.ImageIcon(getClass().getResource("/resource/image/councillors/white.png")));
        councillor.put(ColorCouncillor.BLACK, new javax.swing.ImageIcon(getClass().getResource("/resource/image/councillors/black.png")));

    }

    public void setCommunication(Communication communication) {
        this.communication = communication;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jMenu1 = new javax.swing.JMenu();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jDialog1 = new javax.swing.JDialog();
        kingBonus = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        infoArea = new javax.swing.JTextArea();
        coastBalcony = new javax.swing.JPanel();
        hillsBalcony = new javax.swing.JPanel();
        mountBalcony = new javax.swing.JPanel();
        mountC4 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        profile = new javax.swing.JLayeredPane();
        assistants = new javax.swing.JLabel();
        coins = new javax.swing.JLabel();
        victoryPoints = new javax.swing.JLabel();
        nobility = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        buildEmporiumWithKingButton = new javax.swing.JButton();
        acquirePermitButton = new javax.swing.JButton();
        electCouncillorButton = new javax.swing.JButton();
        buildEmporiumWithPermitButton = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        changePermitTilesButton = new javax.swing.JButton();
        engageAssistantButton = new javax.swing.JButton();
        additionalMainButton = new javax.swing.JButton();
        electWithAssistantButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        buyButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        sellButton = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        passButton = new javax.swing.JButton();
        drawButton = new javax.swing.JButton();
        showPermit = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        userProfile = new javax.swing.JLayeredPane();
        jLabel4 = new javax.swing.JLabel();
        permitHills = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        permitCoast = new javax.swing.JPanel();
        coastPer1 = new javax.swing.JLabel();
        coastPer2 = new javax.swing.JLabel();
        permitMount = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        kingBalcony = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        nobilityTrack = new javax.swing.JLayeredPane();
        jLabel5 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        chatTextField = new javax.swing.JTextField();
        chatSendButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        chatArea = new javax.swing.JTextArea();
        kingCity = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        goldCity = new javax.swing.JLabel();
        silverCity = new javax.swing.JLabel();
        bronzeCity = new javax.swing.JLabel();
        blueCity = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        infoCityPanel = new javax.swing.JPanel();
        infoCity = new javax.swing.JLabel();
        otherPlayer = new javax.swing.JPanel();

        jMenu1.setText("jMenu1");

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Council Of Four");
        setBackground(new java.awt.Color(220, 198, 158));

        kingBonus.setFont(new java.awt.Font("SFNS Display", 0, 11)); // NOI18N
        kingBonus.setText("King bonus:");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Map/coast.png"))); // NOI18N
        jPanel1.add(jLabel7);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Map/hills.png"))); // NOI18N
        jPanel1.add(jLabel9);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Map/mountains.png"))); // NOI18N
        jPanel1.add(jLabel1);

        DefaultCaret caretInfo = (DefaultCaret)infoArea.getCaret();
        caretInfo.setUpdatePolicy(DefaultCaret.ALWAYS_UPDATE);
        infoArea.setEditable(false);
        infoArea.setColumns(20);
        infoArea.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        infoArea.setRows(5);
        jScrollPane3.setViewportView(infoArea);

        coastBalcony.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Coast", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 12))); // NOI18N

        hillsBalcony.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Hills", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 12))); // NOI18N

        mountBalcony.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Mountains", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 12))); // NOI18N
        mountBalcony.add(mountC4);

        profile.setBorder(javax.swing.BorderFactory.createTitledBorder(null, name, javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        profile.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 15, 5));

        assistants.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/image/bonus/assistants.png"))); // NOI18N
        assistants.setText("0");
        profile.add(assistants);

        coins.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/image/bonus/coins.png"))); // NOI18N
        coins.setText("0");
        profile.add(coins);

        victoryPoints.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/image/bonus/victorypoints.png"))); // NOI18N
        victoryPoints.setText("0");
        profile.add(victoryPoints);

        nobility.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/image/bonus/nobilitypoints.png"))); // NOI18N
        nobility.setText("0");
        profile.add(nobility);

        jLabel2.setFont(new java.awt.Font("Georgia", 1, 11)); // NOI18N
        jLabel2.setText("MAIN ACTIONS");

        buildEmporiumWithKingButton.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        buildEmporiumWithKingButton.setText("Build Emporium With King");
        buildEmporiumWithKingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buildEmporiumWithKingButtonActionPerformed(evt);
            }
        });

        acquirePermitButton.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        acquirePermitButton.setText("Acquire Permit");
        acquirePermitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acquirePermitButtonActionPerformed(evt);
            }
        });

        electCouncillorButton.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        electCouncillorButton.setText("Elect Councillor ");
        electCouncillorButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        electCouncillorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                electCouncillorButtonActionPerformed(evt);
            }
        });

        buildEmporiumWithPermitButton.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        buildEmporiumWithPermitButton.setText("Build Emporium With Permit");
        buildEmporiumWithPermitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buildEmporiumWithPermitButtonActionPerformed(evt);
            }
        });

        changePermitTilesButton.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        changePermitTilesButton.setText("Change Permit Tiles");
        changePermitTilesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changePermitTilesButtonActionPerformed(evt);
            }
        });

        engageAssistantButton.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        engageAssistantButton.setText("Engage Assistant");
        engageAssistantButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                engageAssistantButtonActionPerformed(evt);
            }
        });

        additionalMainButton.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        additionalMainButton.setText("Additional Main Action");
        additionalMainButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                additionalMainButtonActionPerformed(evt);
            }
        });

        electWithAssistantButton.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        electWithAssistantButton.setText("Elect Councillor with Assistant");
        electWithAssistantButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                electWithAssistantButtonActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Georgia", 1, 11)); // NOI18N
        jLabel3.setText("QUICK ACTIONS");

        buyButton.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        buyButton.setText("Buy");
        buyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buyButtonActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Georgia", 1, 11)); // NOI18N
        jLabel6.setText("MARKET");

        sellButton.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        sellButton.setText("Sell");
        sellButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sellButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(189, 189, 189))
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(sellButton, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buyButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sellButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(additionalMainButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(electWithAssistantButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(changePermitTilesButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(engageAssistantButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(engageAssistantButton, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(changePermitTilesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(electWithAssistantButton, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(additionalMainButton, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buildEmporiumWithKingButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(acquirePermitButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(electCouncillorButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buildEmporiumWithPermitButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(acquirePermitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(electCouncillorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buildEmporiumWithKingButton, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buildEmporiumWithPermitButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        passButton.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        passButton.setText("Pass");
        passButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passButtonActionPerformed(evt);
            }
        });

        drawButton.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        drawButton.setText("DRAW");
        drawButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drawButtonActionPerformed(evt);
            }
        });

        showPermit.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        showPermit.setText("Show my permits");
        showPermit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showPermitMouseClicked(evt);
            }
        });
        showPermit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showPermitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(showPermit, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(passButton, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(drawButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(showPermit, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passButton)
                    .addComponent(drawButton))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 283, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        userProfile.setBackground(new java.awt.Color(223, 32, 32));
        userProfile.setLayout(new java.awt.FlowLayout());

        jLabel4.setText("playerInfo");
        userProfile.add(jLabel4);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(userProfile)
                            .addComponent(profile, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(profile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(userProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 460, Short.MAX_VALUE))
        );

        permitHills.setLayout(new java.awt.GridLayout(1, 0));

        jLabel11.setText("P1");
        permitHills.add(jLabel11);

        jLabel12.setText("P2");
        permitHills.add(jLabel12);

        permitCoast.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        permitCoast.setLayout(new java.awt.GridLayout(1, 0));

        coastPer1.setText("P1");
        permitCoast.add(coastPer1);

        coastPer2.setText("P2");
        permitCoast.add(coastPer2);

        permitMount.setLayout(new java.awt.GridLayout(1, 0));

        jLabel13.setText("P1");
        permitMount.add(jLabel13);

        jLabel14.setText("P2");
        permitMount.add(jLabel14);

        kingBalcony.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "King", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 12))); // NOI18N

        jLabel17.setText("King");
        kingBalcony.add(jLabel17);

        nobilityTrack.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nobility Track", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 12))); // NOI18N
        nobilityTrack.setLayout(new java.awt.FlowLayout());

        jLabel5.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel5.setText("nobility track");
        nobilityTrack.add(jLabel5);

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.LINE_AXIS));

        chatTextField.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        chatTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chatTextFieldActionPerformed(evt);
            }
        });
        jPanel2.add(chatTextField);

        chatSendButton.setText("Send");
        chatSendButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chatSendButtonActionPerformed(evt);
            }
        });
        jPanel2.add(chatSendButton);

        jPanel4.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 145, 300, -1));

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder("CHAT"));

        chatArea.setEditable(false);
        DefaultCaret caret = (DefaultCaret)infoArea.getCaret();
        caret.setUpdatePolicy(DefaultCaret.ALWAYS_UPDATE);
        chatArea.setColumns(20);
        chatArea.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        chatArea.setRows(5);
        jScrollPane1.setViewportView(chatArea);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 140));

        kingCity.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        kingCity.setText("where is king?");

        jPanel13.setBackground(new java.awt.Color(185, 185, 255));
        jPanel13.setLayout(new java.awt.GridLayout(4, 1));

        goldCity.setBackground(new java.awt.Color(255, 255, 0));
        goldCity.setText("gold");
        goldCity.setOpaque(true);
        jPanel13.add(goldCity);

        silverCity.setBackground(new java.awt.Color(204, 204, 255));
        silverCity.setText("silver");
        silverCity.setOpaque(true);
        jPanel13.add(silverCity);

        bronzeCity.setBackground(new java.awt.Color(204, 153, 0));
        bronzeCity.setText("bronze");
        bronzeCity.setOpaque(true);
        jPanel13.add(bronzeCity);

        blueCity.setBackground(new java.awt.Color(102, 153, 255));
        blueCity.setText("blue");
        blueCity.setOpaque(true);
        jPanel13.add(blueCity);

        jLabel18.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel18.setText("King is in");

        infoCityPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "City info", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 12))); // NOI18N
        infoCityPanel.setLayout(new java.awt.BorderLayout());

        infoCity.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        infoCity.setText("Info CITY");
        infoCityPanel.add(infoCity, java.awt.BorderLayout.PAGE_START);

        otherPlayer.setLayout(new java.awt.GridLayout(2, 1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(mountBalcony, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(coastBalcony, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(permitCoast, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(permitHills, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(permitMount, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(hillsBalcony, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(otherPlayer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(kingCity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(infoCityPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6))
                    .addComponent(nobilityTrack)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(kingBalcony, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(kingBonus, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(hillsBalcony, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                            .addComponent(mountBalcony, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(coastBalcony, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(permitMount, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(permitHills, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(permitCoast, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(kingBalcony, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(kingBonus, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel18)
                                    .addComponent(kingCity, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(infoCityPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(otherPlayer, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nobilityTrack, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.addMouseMotionListener(new MouseMotionListener(){

            @Override
            public void mouseDragged(MouseEvent e){}
            @Override
            public void mouseMoved(MouseEvent e){
                int x=e.getX();
                int y=e.getY();
                System.out.println(x+","+y);//these co-ords are relative to the component
                showToolTips(x,y);
            }
        });

        //jPanel1.addMouseListener(new MouseListener() {
            //    @Override
            //        public void mouseClicked(MouseEvent e) {
                //            int x=e.getX();
                //            int y=e.getY();
                //            System.out.println(x+","+y);//these co-ords are relative to the component
                //showToolTips(x,y);
                //    }
            //@Override
            //        public void mouseExited(MouseEvent e){
                //}
            //@Override
            //        public void mousePressed(MouseEvent e){
                //
                //int x=e.getX();
                //            int y=e.getY();
                //showToolTips(x,y);}
            //@Override
            //        public void mouseReleased(MouseEvent e){}
            //@Override
            //        public void mouseEntered(MouseEvent e){
                // ToolTipManager.sharedInstance().setDismissDelay(100);
                //}
            //});

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void changePermitTilesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changePermitTilesButtonActionPerformed
        ChangePermitTilesDialog changePermitsDialog = new ChangePermitTilesDialog(this, true);
        changePermitsDialog.setPlayerID(playerID);
        changePermitsDialog.setCommunication(communication);
        changePermitsDialog.setVisible(true);
        changePermitsDialog.setAlwaysOnTop(rootPaneCheckingEnabled);
    }//GEN-LAST:event_changePermitTilesButtonActionPerformed

    private void electWithAssistantButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_electWithAssistantButtonActionPerformed
        ElectWithAssistantDialog electWithAssistantDialog = new ElectWithAssistantDialog(this, true);
        electWithAssistantDialog.setPlayerID(playerID);
        electWithAssistantDialog.setCommunication(communication);
        electWithAssistantDialog.setVisible(true);
        electWithAssistantDialog.setAlwaysOnTop(rootPaneCheckingEnabled);
    }//GEN-LAST:event_electWithAssistantButtonActionPerformed

    private void additionalMainButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_additionalMainButtonActionPerformed
        communication.performAdditionalMainAction(playerID);
    }//GEN-LAST:event_additionalMainButtonActionPerformed

    private void engageAssistantButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_engageAssistantButtonActionPerformed
        communication.engage(playerID);
    }//GEN-LAST:event_engageAssistantButtonActionPerformed

    private void buildEmporiumWithKingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buildEmporiumWithKingButtonActionPerformed
        BuildEmporiumWithKingDialog buildWithKingDialog = new BuildEmporiumWithKingDialog(this, true);
        buildWithKingDialog.setPlayerID(playerID);
        buildWithKingDialog.setCommunication(communication);
        buildWithKingDialog.setVisible(true);
        buildWithKingDialog.setAlwaysOnTop(rootPaneCheckingEnabled);
    }//GEN-LAST:event_buildEmporiumWithKingButtonActionPerformed

    private void acquirePermitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acquirePermitButtonActionPerformed
        AcquireBusinessPermitDialog acquirePermitDialog = new AcquireBusinessPermitDialog(this, true);
        acquirePermitDialog.setPlayerID(playerID);
        acquirePermitDialog.setCommunication(communication);
        acquirePermitDialog.setVisible(true);
        acquirePermitDialog.setAlwaysOnTop(rootPaneCheckingEnabled);
    }//GEN-LAST:event_acquirePermitButtonActionPerformed

    private void buildEmporiumWithPermitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buildEmporiumWithPermitButtonActionPerformed
        BuildEmporiumWithPermitDialog buildWithPermitDialog = new BuildEmporiumWithPermitDialog(this, true);
        buildWithPermitDialog.setPlayerID(playerID);
        buildWithPermitDialog.setCommunication(communication);
        buildWithPermitDialog.setVisible(true);
        buildWithPermitDialog.setAlwaysOnTop(rootPaneCheckingEnabled);
    }//GEN-LAST:event_buildEmporiumWithPermitButtonActionPerformed

    private void electCouncillorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_electCouncillorButtonActionPerformed
        ElectCouncillorDialog electCouncillorDialog = new ElectCouncillorDialog(this, true);
        electCouncillorDialog.setPlayerID(playerID);
        electCouncillorDialog.setCommunication(communication);
        electCouncillorDialog.setVisible(true);
        electCouncillorDialog.setAlwaysOnTop(rootPaneCheckingEnabled);
    }//GEN-LAST:event_electCouncillorButtonActionPerformed

    private void showPermitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showPermitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_showPermitActionPerformed

    private void showPermitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showPermitMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_showPermitMouseClicked

    private void passButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passButtonActionPerformed
        if (state.getGamePhase() == GamePhase.TURNS || state.getGamePhase() == GamePhase.FINALTURNS) {
            communication.passTurn(playerID);
        } else if (state.getGamePhase() == GamePhase.MARKET) {
            if (state.getCurrentMarketState() == MarketState.SELLING) {
                communication.sellNone(playerID);
            } else if (state.getCurrentMarketState() == MarketState.BUYING) {
                communication.doneFinishBuying(playerID);
            }
        } else if (state.getGamePhase() == GamePhase.END) {
            JOptionPane.showMessageDialog(null, "The game is over, you cannot pass the turn.", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_passButtonActionPerformed

    private void drawButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drawButtonActionPerformed
        communication.drawCard(playerID);
    }//GEN-LAST:event_drawButtonActionPerformed

    private void chatSendButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chatSendButtonActionPerformed
        String chatMessage = chatTextField.getText();
        communication.chat(playerID, chatMessage);
    }//GEN-LAST:event_chatSendButtonActionPerformed

    private void chatTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chatTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chatTextFieldActionPerformed

    private void buyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buyButtonActionPerformed
        BuyDialog buyDialog = new BuyDialog(this, true, playerID, communication);
        buyDialog.setVisible(true);
        buyDialog.setAlwaysOnTop(rootPaneCheckingEnabled);
    }//GEN-LAST:event_buyButtonActionPerformed

    private void sellButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sellButtonActionPerformed
        SellDialog sellDialog = new SellDialog(this, true, playerID, communication);
        sellDialog.setVisible(true);
        sellDialog.setAlwaysOnTop(rootPaneCheckingEnabled);
    }//GEN-LAST:event_sellButtonActionPerformed

    public static void start() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new GUI(playerID,communication).setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton acquirePermitButton;
    private javax.swing.JButton additionalMainButton;
    private javax.swing.JLabel assistants;
    private javax.swing.JLabel blueCity;
    private javax.swing.JLabel bronzeCity;
    private javax.swing.JButton buildEmporiumWithKingButton;
    private javax.swing.JButton buildEmporiumWithPermitButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton buyButton;
    private javax.swing.JButton changePermitTilesButton;
    private javax.swing.JTextArea chatArea;
    private javax.swing.JButton chatSendButton;
    private javax.swing.JTextField chatTextField;
    private javax.swing.JPanel coastBalcony;
    private javax.swing.JLabel coastPer1;
    private javax.swing.JLabel coastPer2;
    private javax.swing.JLabel coins;
    private javax.swing.JButton drawButton;
    private javax.swing.JButton electCouncillorButton;
    private javax.swing.JButton electWithAssistantButton;
    private javax.swing.JButton engageAssistantButton;
    private javax.swing.JLabel goldCity;
    private javax.swing.JPanel hillsBalcony;
    private javax.swing.JTextArea infoArea;
    private javax.swing.JLabel infoCity;
    private javax.swing.JPanel infoCityPanel;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel kingBalcony;
    private javax.swing.JLabel kingBonus;
    private javax.swing.JLabel kingCity;
    private javax.swing.JPanel mountBalcony;
    private javax.swing.JLabel mountC4;
    private javax.swing.JLabel nobility;
    private javax.swing.JLayeredPane nobilityTrack;
    private javax.swing.JPanel otherPlayer;
    private javax.swing.JButton passButton;
    private javax.swing.JPanel permitCoast;
    private javax.swing.JPanel permitHills;
    private javax.swing.JPanel permitMount;
    private javax.swing.JLayeredPane profile;
    private javax.swing.JButton sellButton;
    private javax.swing.JButton showPermit;
    private javax.swing.JLabel silverCity;
    private javax.swing.JLayeredPane userProfile;
    private javax.swing.JLabel victoryPoints;
    // End of variables declaration//GEN-END:variables

    public void setPlayerName(String name) {
        this.name = name;
        profile.setBorder(javax.swing.BorderFactory.createTitledBorder(null, name, javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

    }

    public JTextArea getChatArea() {
        return chatArea;
    }

    public JTextArea getInfoArea() {
        return infoArea;
    }

    public JLabel getAssistants() {
        return assistants;
    }

    public JLabel getNobility() {
        return nobility;
    }

    public JLabel getCoins() {
        return coins;
    }

    public JLabel getVictoryPoints() {
        return victoryPoints;
    }

    public JLayeredPane getUserProfile() {
        return userProfile;
    }

    public void setState(State gameState) {
        this.state = gameState;
    }

    public void showPoliticCard(ColorPolitic c) {
        JLabel politic = (new javax.swing.JLabel());

        if (c == ColorPolitic.BLACK) {
            politic.setIcon(politicCard.get(ColorPolitic.BLACK));
        }
        if (c == ColorPolitic.ORANGE) {
            politic.setIcon(politicCard.get(ColorPolitic.ORANGE));
        }
        if (c == ColorPolitic.BLUE) {
            politic.setIcon(politicCard.get(ColorPolitic.BLUE));
        }
        if (c == ColorPolitic.JOLLY) {
            politic.setIcon(politicCard.get(ColorPolitic.JOLLY));
        }
        if (c == ColorPolitic.PINK) {
            politic.setIcon(politicCard.get(ColorPolitic.PINK));
        }
        if (c == ColorPolitic.PURPLE) {
            politic.setIcon(politicCard.get(ColorPolitic.PURPLE));
        }
        if (c == ColorPolitic.WHITE) {
            politic.setIcon(politicCard.get(ColorPolitic.WHITE));

        }
        userProfile.add(politic);
        userProfile.revalidate();
        userProfile.repaint();

    }

    public void showCouncillor(Balcony b, RegionType rt) {
        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                JLabel coun;
                JPanel balc = null;
                if (rt == RegionType.COAST) {
                    coastBalcony.removeAll();
                    balc = coastBalcony;

                }
                if (rt == RegionType.HILLS) {
                    hillsBalcony.removeAll();
                    balc = hillsBalcony;

                }
                if (rt == RegionType.MOUNTAINS) {
                    mountBalcony.removeAll();
                    balc = mountBalcony;

                }
                if (rt == null) {
                    kingBalcony.removeAll();
                    balc = kingBalcony;

                }
                // colorare le carte

                for (ColorCouncillor c : b.readBalcony()) {
                    coun = new javax.swing.JLabel();
                    if (c == ColorCouncillor.BLACK) {
                        coun.setIcon(councillor.get(ColorCouncillor.BLACK));
                    }
                    if (c == ColorCouncillor.ORANGE) {
                        coun.setIcon(councillor.get(ColorCouncillor.ORANGE));
                    }
                    if (c == ColorCouncillor.BLUE) {
                        coun.setIcon(councillor.get(ColorCouncillor.BLUE));
                    }
                    if (c == ColorCouncillor.PINK) {
                        coun.setIcon(councillor.get(ColorCouncillor.PINK));
                    }
                    if (c == ColorCouncillor.PURPLE) {
                        coun.setIcon(councillor.get(ColorCouncillor.PURPLE));
                    }
                    if (c == ColorCouncillor.WHITE) {
                        coun.setIcon(councillor.get(ColorCouncillor.WHITE));
                    }
                    if (balc != null) {
                        balc.add(coun);
                        balc.revalidate();
                        balc.repaint();
                    }

                }

            }
        });
    }

    public JPanel getCoastBalcony() {
        return coastBalcony;
    }

    public JPanel getHillsBalcony() {
        return hillsBalcony;
    }

    public JPanel getMountBalcony() {
        return mountBalcony;
    }

    public JPanel getKingBalcony() {
        return kingBalcony;
    }

    public JLabel getkingBonus() {
        return kingBonus;
    }

    public JLayeredPane getnobilityTrack() {
        return nobilityTrack;
    }

    public void showPermit(BusinessPermit[] bp, RegionType rt) {
        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                JPanel reg = null;
                JLabel per;
                if (rt == RegionType.COAST) {
                    reg = permitCoast;
                }
                if (rt == RegionType.HILLS) {
                    reg = permitHills;
                }
                if (rt == RegionType.MOUNTAINS) {
                    reg = permitMount;
                }
                if (reg != null) {
                    reg.removeAll();
                    for (BusinessPermit b : bp) {
                        per = new JLabel("<html>ID: " + b.getId() + "<br>City:" + b.getCityNames().toString() + "<br>Bonus:" + b.getBonusList().toString() + "</html>");
                        per.setFont(new java.awt.Font("Arial", 0, 11));
                        per.setVisible(true);
                        reg.add(per);
                        reg.revalidate();
                        reg.repaint();
                    }
                }
            }

        });
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                prova();
                GUI guiWindow = new GUI(0, "ubaldo", null);
                guiWindow.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                guiWindow.setVisible(true);
            }
        });
    }

    public JLabel getKingCity() {
        return kingCity;
    }

    public JLabel getGoldCity() {
        return goldCity;
    }

    public JLabel getSilverCity() {
        return silverCity;
    }

    public JLabel getBronzeCity() {
        return bronzeCity;
    }

    public JLabel getBlueCity() {
        return blueCity;
    }

    private Map<Point, String> mapCoordinates;
    private Map<String, String> cityDesc;
//    private static void prova() {
//        mapCoordinates = new HashMap<>();
//        mapCoordinates.put(new Point(58, 55), "allah akbar");
//        mapCoordinates.put(new Point(42, 163), "bileeee");
//        cityDesc = new HashMap<>();
//        cityDesc.put("allah akbar", "bonus:ciwawa<br>ciaciao");
//        cityColor = new HashMap<>();
//        cityColor.put("allah akbar", ColorCity.BLUE);
//    }
    public void nobilityRequest(State state) {
        NobilityRequestDialog requestDialog = new NobilityRequestDialog(this, true, playerID, communication, state);
        requestDialog.setVisible(true);
        requestDialog.setAlwaysOnTop(rootPaneCheckingEnabled);
    }

    public Map<String, String> getCityDesc() {
        return cityDesc;
    }

    public void showToolTips(int x, int y) {
        if (mapCoordinates != null) {
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    Point userMouse = new Point(x, y);
                    for (Map.Entry<Point, String> cityCoord : mapCoordinates.entrySet()) {
                        if (isNear(userMouse, cityCoord.getKey())) {

                            JLabel infoCity = new JLabel("<html>" + cityDesc.get(cityCoord.getValue()) + "</html>");
                            infoCity.setFont(new java.awt.Font("Arial", 0, 12));
                            infoCityPanel.removeAll();
                            infoCityPanel.add(infoCity);
                            infoCityPanel.revalidate();
                            infoCityPanel.repaint();
                        }
                    }
                }
            });
        }
    }

    private boolean isNear(Point user, Point city) {
        if (user.distance(city) < 20) {
            return true;
        }
        return false;
    }

    public void buildMap(String coastFilename, String hillsFilename, String mountainsFilename, Map<Point, String> positions) {
        // carica immagini dai filename
        // disegna la mappa
        // setta la variabile positions
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource(coastFilename))); // NOI18N
                jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource(hillsFilename))); // NOI18N
                jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource(mountainsFilename))); // NOI18N
                jPanel1.revalidate();
                mapCoordinates = new HashMap<>(positions);
                cityDesc = new HashMap<>();

            }
        });

        //FIXME ricordarsi di togliere il disegnare la mappa dal main (va tenuto solo qua)
    }
    public JPanel getOtherPlayerArea(){
        return otherPlayer;
    }
}
