/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package it.polimi.ingsw.ps14.client.view.gui;

import it.polimi.ingsw.ps14.client.Communication;
import it.polimi.ingsw.ps14.model.State;
import it.polimi.ingsw.ps14.model.WaitingFor;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;

/**
 *
 * @author peter
 */
public class NobilityRequestDialog extends javax.swing.JDialog {

	private final transient Integer playerID;
	private final transient Communication communication;
	private final State state;
	private final Map<JCheckBox, String> checkboxes;
	
	/**
	 * Creates new form NobilityRequestDialog
	 */
	public NobilityRequestDialog(java.awt.Frame parent, boolean modal, Integer playerID, Communication communication, State state) {
		super(parent, modal);
		this.playerID = playerID;
		this.communication = communication;
		this.state = state;
		
		initComponents();
				
		// set description
		descriptionLabel.setText("");
		descriptionLabel.repaint();
		descriptionLabel.revalidate();
		// set description number of choices
		numberChoicesLabel.setText("");
		numberChoicesLabel.repaint();
		numberChoicesLabel.revalidate();
		
		// costruisci una checkbox per ogni choice
		// metti ogni checkbox in una lista
		Map<String, String> choices = state.getAvailableChoices();
		checkboxes = new HashMap<>();
		for (Map.Entry<String, String> choice : choices.entrySet())
		{
			JCheckBox checkbox = new JCheckBox(choice.getValue());
			checkboxes.put(checkbox, choice.getKey());
			choicesPanel.add(checkbox);
			choicesPanel.repaint();
			choicesPanel.revalidate();
		}

		pack();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        descriptionLabel = new javax.swing.JLabel();
        choicesPanel = new javax.swing.JPanel();
        confirmButton = new javax.swing.JButton();
        numberChoicesLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        titleLabel.setText("Nobility Request");

        descriptionLabel.setText("[description]");

        javax.swing.GroupLayout choicesPanelLayout = new javax.swing.GroupLayout(choicesPanel);
        choicesPanel.setLayout(choicesPanelLayout);
        choicesPanelLayout.setHorizontalGroup(
            choicesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 194, Short.MAX_VALUE)
        );
        choicesPanelLayout.setVerticalGroup(
            choicesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 77, Short.MAX_VALUE)
        );

        confirmButton.setText("Confirm");
        confirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmButtonActionPerformed(evt);
            }
        });

        numberChoicesLabel.setText("[number of available choices]");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 108, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(numberChoicesLabel)
                    .addComponent(choicesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(98, 98, 98))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(titleLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(descriptionLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(confirmButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLabel)
                .addGap(18, 18, 18)
                .addComponent(descriptionLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(numberChoicesLabel)
                .addGap(18, 18, 18)
                .addComponent(choicesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(confirmButton)
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void confirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmButtonActionPerformed
		// get choices 
		// for each entry in checkboxes
		// if checkbox is selected, add value (id) to list of ids chosen
		List<String> choices = new ArrayList();
		
		for (Map.Entry<JCheckBox, String> entry : checkboxes.entrySet())
		{
			if (entry.getKey().isSelected()) {
				choices.add(entry.getValue());
			}
		}
		
		if (choices.size() <= state.getWaitingForHowMany()) {
			communication.answerNobilityRequest(playerID, choices);
			dispose();
		} else {
			JOptionPane.showMessageDialog(null, String.format("You cannot select more than %d", state.getWaitingForHowMany()), "Warning", JOptionPane.WARNING_MESSAGE);
			return;
		}
    }//GEN-LAST:event_confirmButtonActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(NobilityRequestDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(NobilityRequestDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(NobilityRequestDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(NobilityRequestDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the dialog */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				State fakeState = new State();
				fakeState.setWaitingFor(WaitingFor.FROMPERMITS);
				fakeState.setWaitingForHowMany(2);
				Map<String, String> availableChoices = new HashMap<>();
				availableChoices.put("12", "Permit no. 12/nBonus: +1 point");
				availableChoices.put("45", "Permit no. 45/nBonus: +1 nobility, +3 cards");
				availableChoices.put("102", "Permit no. 1027nBonus: none");
				fakeState.setAvailableChoices(availableChoices);
				NobilityRequestDialog dialog = new NobilityRequestDialog(new javax.swing.JFrame(), true, 0, null, new State());
				dialog.addWindowListener(new java.awt.event.WindowAdapter() {
					@Override
					public void windowClosing(java.awt.event.WindowEvent e) {
						System.exit(0);
					}
				});
				dialog.setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel choicesPanel;
    private javax.swing.JButton confirmButton;
    private javax.swing.JLabel descriptionLabel;
    private javax.swing.JLabel numberChoicesLabel;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
