package it.polimi.ingsw.ps14.client.view.gui;

import it.polimi.ingsw.ps14.client.Communication;
import it.polimi.ingsw.ps14.model.ColorPolitic;
import it.polimi.ingsw.ps14.model.ItemForSale;
import it.polimi.ingsw.ps14.model.ItemForSale.ItemForSaleType;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author nicol
 */
public class SellDialog extends javax.swing.JDialog {
	
	private final transient Integer playerID;
	private final transient Communication communication;

    /**
     * Creates new form SellDialog
     */
    public SellDialog(java.awt.Frame parent, boolean modal, Integer playerID, Communication communication) {
        super(parent, modal);
		this.playerID = playerID;
		this.communication = communication;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jSpinnerPurple = new javax.swing.JSpinner();
        jSpinnerPink = new javax.swing.JSpinner();
        jSpinnerWhite = new javax.swing.JSpinner();
        jSpinnerBlue = new javax.swing.JSpinner();
        jSpinnerOrange = new javax.swing.JSpinner();
        jSpinnerJolly = new javax.swing.JSpinner();
        jLabel13 = new javax.swing.JLabel();
        sellButton = new javax.swing.JButton();
        pricePurpleTextField = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        pricePinkTextField = new javax.swing.JTextField();
        priceWhiteTextField = new javax.swing.JTextField();
        priceBlueTextField = new javax.swing.JTextField();
        priceOrangeTextField = new javax.swing.JTextField();
        priceJollyTextField = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 32767));
        priceAssistantTextField = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jSpinnerAssistants = new javax.swing.JSpinner();
        jLabel12 = new javax.swing.JLabel();
        jSpinnerBlack = new javax.swing.JSpinner();
        priceBlackTextField = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        permitIDField3 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        permitPriceField2 = new javax.swing.JTextField();
        permitPriceField1 = new javax.swing.JTextField();
        permitIDField1 = new javax.swing.JTextField();
        permitPriceField3 = new javax.swing.JTextField();
        permitIDField2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Sell");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Assistants");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Cards");

        jLabel6.setText("PINK");

        jLabel7.setText("PURPLE");

        jLabel8.setText("WHITE");

        jLabel9.setText("BLUE");

        jLabel10.setText("ORANGE");

        jLabel11.setText("JOLLY");

        jSpinnerPurple.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        jSpinnerPink.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        jSpinnerWhite.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        jSpinnerBlue.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        jSpinnerOrange.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        jSpinnerJolly.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setText("Business Permits (ID-Price,ID-price,...)");

        sellButton.setText("Sell");
        sellButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sellButtonActionPerformed(evt);
            }
        });

        jLabel14.setText("Price");

        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel4.setText("Price for one assistant");
        jPanel1.add(jLabel4, java.awt.BorderLayout.CENTER);
        jPanel1.add(filler1, java.awt.BorderLayout.PAGE_START);

        priceAssistantTextField.setMinimumSize(new java.awt.Dimension(50, 32));
        priceAssistantTextField.setPreferredSize(new java.awt.Dimension(50, 32));
        jPanel1.add(priceAssistantTextField, java.awt.BorderLayout.LINE_END);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jLabel3.setText("Amount you want to sell");
        jPanel2.add(jLabel3, java.awt.BorderLayout.CENTER);

        jSpinnerAssistants.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        jPanel2.add(jSpinnerAssistants, java.awt.BorderLayout.LINE_END);

        jLabel12.setText("BLACK");

        jSpinnerBlack.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        jLabel16.setText("ID");

        jLabel15.setText("Price");

        permitIDField1.setPreferredSize(new java.awt.Dimension(50, 32));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(permitIDField3)
                        .addComponent(permitIDField2)
                        .addComponent(permitIDField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(permitPriceField3)
                    .addComponent(permitPriceField2)
                    .addComponent(permitPriceField1))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(permitIDField1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(permitIDField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(permitIDField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(permitPriceField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(permitPriceField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(permitPriceField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2)
                        .addComponent(jLabel13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel5)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jSpinnerOrange, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jSpinnerJolly, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jSpinnerBlue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jSpinnerWhite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jSpinnerPink, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jSpinnerPurple, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel12)
                                    .addGap(53, 53, 53)
                                    .addComponent(jSpinnerBlack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(5, 5, 5)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(87, 87, 87)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(priceOrangeTextField)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(priceBlueTextField)
                    .addComponent(priceWhiteTextField)
                    .addComponent(pricePinkTextField)
                    .addComponent(pricePurpleTextField)
                    .addComponent(priceJollyTextField)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(priceBlackTextField)))
                .addGap(46, 46, 46))
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(sellButton, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jSpinnerPurple, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pricePurpleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jSpinnerPink, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pricePinkTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jSpinnerOrange, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(priceOrangeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jSpinnerWhite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(priceWhiteTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jSpinnerBlue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(priceBlueTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(jSpinnerBlack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(priceBlackTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jSpinnerJolly, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(priceJollyTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(sellButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sellButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sellButtonActionPerformed
		List<ItemForSale> items = new ArrayList<>();

		try {
		
			Integer numAssistants = (Integer) jSpinnerAssistants.getValue();
			if (numAssistants > 0) {
				Integer priceAssistants;
				priceAssistants = Integer.valueOf(priceAssistantTextField.getText());
				items.add(new ItemForSale(ItemForSaleType.ASSISTANT, numAssistants, priceAssistants, playerID));
			}

			String permitText1 = permitIDField1.getText();
			if (!permitText1.isEmpty()) {
				Integer permitID1;
				permitID1 = Integer.valueOf(permitText1);
				Integer pricePermit1 = Integer.valueOf(permitPriceField1.getText());
				items.add(new ItemForSale(ItemForSaleType.BUSINESS, permitID1, pricePermit1, playerID));
			}

			String permitText2 = permitIDField2.getText();
			if (!permitText2.isEmpty()) {
				Integer permitID2;
				permitID2 = Integer.valueOf(permitText2);
				Integer pricePermit2 = Integer.valueOf(permitPriceField2.getText());
				items.add(new ItemForSale(ItemForSaleType.BUSINESS, permitID2, pricePermit2, playerID));
			}

			String permitText3 = permitIDField3.getText();
			if (!permitText3.isEmpty()) {
				Integer permitID3;
				permitID3 = Integer.valueOf(permitText3);
				Integer pricePermit3 = Integer.valueOf(permitPriceField3.getText());
				items.add(new ItemForSale(ItemForSaleType.BUSINESS, permitID3, pricePermit3, playerID));
			}
			
			Integer purpleCards = (Integer) jSpinnerPurple.getValue();
			if (purpleCards > 0) {
				String purplePrice = pricePurpleTextField.getText();
				if (purplePrice.isEmpty()) {
					JOptionPane.showMessageDialog(null, "You must enter a price for the cards you want to sell", "Warning", JOptionPane.WARNING_MESSAGE);
					return;
				}
				for (int i=0; i<purpleCards; i++) {
					items.add(new ItemForSale(ColorPolitic.PURPLE, Integer.valueOf(purplePrice), playerID));
				}
			}
			
			Integer pinkCards = (Integer) jSpinnerPink.getValue();
			if (pinkCards > 0) {
				String pinkPrice = pricePinkTextField.getText();
				if (pinkPrice.isEmpty()) {
					JOptionPane.showMessageDialog(null, "You must enter a price for the cards you want to sell", "Warning", JOptionPane.WARNING_MESSAGE);
					return;
				}
				for (int i=0; i<pinkCards; i++) {
					items.add(new ItemForSale(ColorPolitic.PINK, Integer.valueOf(pinkPrice), playerID));
				}
			}
			
			Integer orangeCards = (Integer) jSpinnerOrange.getValue();
			if (orangeCards > 0) {
				String orangePrice = priceOrangeTextField.getText();
				if (orangePrice.isEmpty()) {
					JOptionPane.showMessageDialog(null, "You must enter a price for the cards you want to sell", "Warning", JOptionPane.WARNING_MESSAGE);
					return;
				}
				for (int i=0; i<orangeCards; i++) {
					items.add(new ItemForSale(ColorPolitic.ORANGE, Integer.valueOf(orangePrice), playerID));
				}
			}
			
			Integer whiteCards = (Integer) jSpinnerWhite.getValue();
			if (whiteCards > 0) {
				String whitePrice = priceWhiteTextField.getText();
				if (whitePrice.isEmpty()) {
					JOptionPane.showMessageDialog(null, "You must enter a price for the cards you want to sell", "Warning", JOptionPane.WARNING_MESSAGE);
					return;
				}
				for (int i=0; i<whiteCards; i++) {
					items.add(new ItemForSale(ColorPolitic.WHITE, Integer.valueOf(whitePrice), playerID));
				}
			}
			
			Integer blueCards = (Integer) jSpinnerBlue.getValue();
			if (blueCards > 0) {
				String blackPrice = priceBlueTextField.getText();
				if (blackPrice.isEmpty()) {
					JOptionPane.showMessageDialog(null, "You must enter a price for the cards you want to sell", "Warning", JOptionPane.WARNING_MESSAGE);
					return;
				}
				for (int i=0; i<blueCards; i++) {
					items.add(new ItemForSale(ColorPolitic.BLUE, Integer.valueOf(blackPrice), playerID));
				}
			}
			
			Integer blackCards = (Integer) jSpinnerBlack.getValue();
			if (blackCards > 0) {
				String blackPrice = priceBlackTextField.getText();
				if (blackPrice.isEmpty()) {
					JOptionPane.showMessageDialog(null, "You must enter a price for the cards you want to sell", "Warning", JOptionPane.WARNING_MESSAGE);
					return;
				}
				for (int i=0; i<blackCards; i++) {
					items.add(new ItemForSale(ColorPolitic.BLACK, Integer.valueOf(blackPrice), playerID));
				}
			}
			
			Integer jollyCards = (Integer) jSpinnerJolly.getValue();
			if (jollyCards > 0) {
				String jollyPrice = priceJollyTextField.getText();
				if (jollyPrice.isEmpty()) {
					JOptionPane.showMessageDialog(null, "You must enter a price for the cards you want to sell", "Warning", JOptionPane.WARNING_MESSAGE);
					return;
				}
				for (int i=0; i<jollyCards; i++) {
					items.add(new ItemForSale(ColorPolitic.JOLLY, Integer.valueOf(jollyPrice), playerID));
				}
			}

		
			if (items.isEmpty()) {
				communication.sellNone(playerID);
				dispose();
			} else {
				communication.sell(playerID, items);
				dispose();
			}
		
		} catch (NumberFormatException e) {
			JOptionPane.showMessageDialog(null, "You can only enter numbers in the id and price fields", "Warning", JOptionPane.WARNING_MESSAGE);
			return;
		}
    }//GEN-LAST:event_sellButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SellDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SellDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SellDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SellDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SellDialog dialog = new SellDialog(new javax.swing.JFrame(), true, 0, null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSpinner jSpinnerAssistants;
    private javax.swing.JSpinner jSpinnerBlack;
    private javax.swing.JSpinner jSpinnerBlue;
    private javax.swing.JSpinner jSpinnerJolly;
    private javax.swing.JSpinner jSpinnerOrange;
    private javax.swing.JSpinner jSpinnerPink;
    private javax.swing.JSpinner jSpinnerPurple;
    private javax.swing.JSpinner jSpinnerWhite;
    private javax.swing.JTextField permitIDField1;
    private javax.swing.JTextField permitIDField2;
    private javax.swing.JTextField permitIDField3;
    private javax.swing.JTextField permitPriceField1;
    private javax.swing.JTextField permitPriceField2;
    private javax.swing.JTextField permitPriceField3;
    private javax.swing.JTextField priceAssistantTextField;
    private javax.swing.JTextField priceBlackTextField;
    private javax.swing.JTextField priceBlueTextField;
    private javax.swing.JTextField priceJollyTextField;
    private javax.swing.JTextField priceOrangeTextField;
    private javax.swing.JTextField pricePinkTextField;
    private javax.swing.JTextField pricePurpleTextField;
    private javax.swing.JTextField priceWhiteTextField;
    private javax.swing.JButton sellButton;
    // End of variables declaration//GEN-END:variables
}
